# Generated by Django 5.2.1 on 2025-05-20 20:21

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplates', '0006_auto_20171116_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='base_template',
            field=models.CharField(blank=True, help_text="If present, the name of a django template.<br/> The body field will be present as the 'email_body' context variable", max_length=1024),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_address',
            field=models.CharField(blank=True, help_text="Specify as: 'Full Name &lt;email@address>'<br/>Defaults to: 'no-reply@site.domain'", max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='txt_body',
            field=models.TextField(blank=True, help_text='If present, use as the plain-text body', null=True),
        ),
    ]
